### ISSUE TITLE
Move Okta setup above CloudFormation deployment

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#10]
These parameters in the CloudFormation deployment are dependent on the Okta configuration:

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L135

I'd suggest the Okta setup section is put before the CloudFormation deployment.

**Comment by kevhiggi** [comment]
The SPA setup in Okta requires output values from the CloudFormation stack
