### ISSUE TITLE
Adding a Groups claim to ID tokens - guidance

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#11]
Groups claim name must be all lower case! as it’s expected by the SPA code to be lower: `groups`

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L210

Please make this very clear in the guidance, as the current reference has it proper case which does not work.

Please include guidance for the other fields for Okta configuration - such as Filter and Regex

Am screen shot of an example Okta configuration could be useful.

**Comment by dboyd13** [comment]
Example

![Screen Shot 2022-05-19 at 2 45 00 pm](https://user-images.githubusercontent.com/3401492/169425083-a1f05f3f-acfb-4c1d-a51f-6fccc624ed14.png)

**Comment by kevhiggi** [comment]
Updated README.md
