### ISSUE TITLE
ApiGatewayKeyValue contains the CLI command to get the key - Guidance update

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#14]
`ApiGatewayKeyValue` contains the CLI command to get the key - not the key, this should be clear with steps to get the key (e.g. via Cloud9 environment)

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L270

**Comment by kevhiggi** [comment]
Updated README.md
