### ISSUE TITLE
/public/index.html - APIEndpoint -> ServiceEndpoint

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#16]
Suggest referencing the actual CloudFormation output name (`ServiceEndpoint`) instead of (`APIEndpoint`)

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L323

Also, remove `https://` prefix as the CloudFormation output already has it

**Comment by kevhiggi** [comment]
Updated README.md
