### ISSUE TITLE
SNS - Create & validate an email before CloudFormation Deploy

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#18]
Create & validate an email to be used by SNS before CloudFormation deployment

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L126

**Comment by kevhiggi** [comment]
The README.md already contains the following note under the 'Notifications Setup' section:
"This email address must be either individually verified with Amazon SES, or from a domain that has been verified with Amazon SES. For information about verifying identities, see the [Amazon SES Developer Guide](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/verify-addresses-and-domains.html)"
