### ISSUE TITLE
npm install build has vulnerabilities

### ISSUE THREAD

**Issue by worldofdub** [aws-samples/aws-iam-temporary-elevated-access-broker#20]
npm install

added 2596 packages, and audited 2597 packages in 1m

246 packages are looking for funding
  run `npm fund` for details

27 vulnerabilities (10 moderate, 15 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

**Comment by kevhiggi** [comment]
Updated react-scripts to 5.0.1
