### ISSUE TITLE
Failed to compile : ui-frontend\src\components\AppLayout\index.tsx

### ISSUE THREAD

**Issue by markyates** [aws-samples/aws-iam-temporary-elevated-access-broker#3]
Failed to compile.

TS2322: Type '{ header: { text: string; href: string; }; expanded: boolean; items: SideNavigationItem[]; }' is not assignable to type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<Pick<SideNavigationProps, "header" | "items"> & ({} | { wrappedComponentRef?: Ref<any> | undefined; }), any, any>> & (Readonly<...> & Readonly<...>))'.
  Property 'expanded' does not exist on type 'IntrinsicAttributes & (IntrinsicClassAttributes<Component<Pick<SideNavigationProps, "header" | "items"> & ({} | { wrappedComponentRef?: Ref<any> | undefined; }), any, any>> & (Readonly<...> & Readonly<...>))'.
    17 |     return <SideNavigationBase
    18 |         header={{text: 'Demo', href: '/'}}
  > 19 |         expanded={false}
       |         ^^^^^^^^
    20 |         items={
    21 |           getNavigation()
    22 |         }

**Comment by markyates** [comment]
Builds with:

    return <SideNavigationBase
        header={{text: 'Demo', href: '/'}}
        /*expanded={false}*/
        items={
          getNavigation()

**Comment by kevhiggi** [comment]
Thanks for reporting the issue. NorthStar makes changes from one build to another build and sometimes they are not backward compatible. We will have an update shortly.

**Comment by kevhiggi** [comment]
NorthStar will be adding an expandedAll props in the SideNavigation in a future release - for now, we have removed the expanded property in the code.
