### ISSUE TITLE
Create Request Form Not Triggering onChange Event

### ISSUE THREAD

**Issue by paulmowat** [aws-samples/aws-iam-temporary-elevated-access-broker#5]
Hi,

I've followed through the steps and got everything deployed and configured as expected I believe.

I can successfully login and from debugging I can see the groups coming through as expected from the IDP in the HomePageContent.tsx createAccountMap function.

When I navigate to the create request form I can select the account, however this doesn't trigger the onChange event to populate the role and I cannot select that.

I've added some console.logs to the onChange events and I can't see any of them being triggered when the form input is changed.

I'm using Chrome version 98.0.4758.102, also checked in edge 98.0.1108.55 and had the same.

Any ideas?

Thanks

Paul

**Comment by paulmowat** [comment]
After debugging further I tried fixing the aws-northstar package to 1.3.8 and it started to work. 

Would appear to be a issue with a newer version of that package. Would recommend to fix the package versions in the package.json and/or commit the package-lock.json file to avoid issues like this.

**Comment by kevhiggi** [comment]
Updating typscript version range, okta-react and compiler options in tsconfig

**Comment by kevhiggi** [comment]
Updated typscript version range, okta-react and compiler options in tsconfig
