### ISSUE TITLE
npm build failed : Property 'groups' does not exist 

### ISSUE THREAD

**Issue by wellsiau-aws** [aws-samples/aws-iam-temporary-elevated-access-broker#6]
**Error**

Property 'groups' does not exist on type '{ auth_time?: number | undefined; aud?: string | undefined; email?: string | undefined; email_verified?: boolean | undefined; exp?: number | undefined; family_name?: string | undefined; ... 12 more ...; at_hash?: string | undefined; }'.  TS2339
```
    83 |         const claims = await oktaAuth.getUser();
    84 |         userInfo.user = claims.email ? claims.email : "";
  > 85 |         userInfo.accountMap = createAccountMap(claims.groups);
       |                                                       ^
    86 | 
    87 |         const tokenManager = oktaAuth.tokenManager;
    88 |         const accessToken = await tokenManager.get('accessToken');
```

**Step to replicate**

1. Run `npm run build` on **ui-frontend**
2. npm  package.json is set to **"@okta/okta-react": "^6.3.0"**

**Temp fix**
pin @okta/okta-react to version 6.3.0

**Comment by kevhiggi** [comment]
The okta-react is "downstream" from okta-auth-js so whenever a new version of okta-auth-js is released there is a moment in time before the downstream SDKs are updated. As a temporary fix, I have locked the okta-react module to version 6.3.0.
