### ISSUE TITLE
Improve CloudFormation guidance

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#8]
The current guidance for CloudFormation deployment does not cover the steps/guidance to get the template from the Cloud9 environment to either an S3 bucket or local file such that it can be deployed via the AWS Management Console

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L124

**Comment by kevhiggi** [comment]
Updated README.md
