### ISSUE TITLE
Improve CloudFormation guidance - parameter order

### ISSUE THREAD

**Issue by dboyd13** [aws-samples/aws-iam-temporary-elevated-access-broker#9]
Suggest that the listed bullets in the same order as they appear on the CloudFormation console page

https://github.com/aws-samples/aws-iam-temporary-elevated-access-broker/blob/ce85fa42b2a640f6502b6adae0513cc7e4f1be1b/README.md?plain=1#L125

**Comment by dboyd13** [comment]
Example:

![Screen Shot 2022-05-20 at 10 30 45 am](https://user-images.githubusercontent.com/3401492/169425457-41c027f7-ef38-4207-b452-55f6fb3a6fee.png)

**Comment by kevhiggi** [comment]
Updated README.md
